### ISSUE TITLE
RIOT API Request 400 error

### ISSUE THREAD

**Issue by HyeJung-Hwang** [boaz-lol/lp-patchnote#6]
`{'status': {'message': 'Bad Request - Exception decrypting 4uVgqR3NP5eJYijTMzTNQcn7fE0WuUxJPAHQ02YB4UELWBYTFh1htmL3NWekWThhhog24g7zKj7U2w', 'status_code': 400}}`
위 에러가 일요일날 전달받은 코드에서 다시 발생하여 구글링을  좀 해보니 아래 이슈가 있네요!!

https://github.com/RiotGames/developer-relations/issues/759

puid 구하는 코드를 전달해주시면 제가 제 API key 통해서 puid 구해서 쓰거나 데이터셋 전달받아서 쓰는 게 좋을 듯 합니다!

**Comment by HyeJung-Hwang** [comment]
@sunnyineverywhere 확인해주시면 감사함미당

**Comment by wangzhatt24** [comment]
I am getting the same error, I tried asking for a new api key and calling it all from my backend app but still not working, but using riot developer portal it works fine

**Comment by wangzhatt24** [comment]
I am getting the same error, I tried asking for a new api key and calling it all from my backend app but still not working, but using riot developer portal it works fine
